# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iixVFJvmSvuq_A4E2YzyWfcw3guLz7TA
"""

# 1) Install
!pip install gradio scikit-learn

# 2) Imports
import gradio as gr
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression


# 3) Dataset (simple demo)

data = {
    "query": [
        "SELECT * FROM users",
        "SELECT name FROM products WHERE id=1",
        "admin' OR '1'='1",
        "' OR 1=1 --",
        "DROP TABLE users",
        "SELECT * FROM accounts WHERE username='admin' AND password='1234'",
        "'; DELETE FROM users --",
        "hello world",
        "normal search",
        "SELECT email FROM customers"
    ],
    "label": [0,0,1,1,1,0,1,0,0,0]
}

df = pd.DataFrame(data)


# 4) Train model

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["query"])
y = df["label"]

model = LogisticRegression()
model.fit(X, y)


# 5) Prediction function

def detect_sql_injection(query):
    vec = vectorizer.transform([query])
    pred = model.predict(vec)[0]

    if pred == 1:
        return "⚠️ SQL Injection Detected!"
    else:
        return "✅ Normal Query"


# 6) Create Website UI

demo = gr.Interface(
    fn=detect_sql_injection,
    inputs=gr.Textbox(lines=3, placeholder="Enter SQL query here..."),
    outputs="text",
    title="SQL Injection Detector",
    description="Enter a SQL query to check if it's malicious or safe."
)


# 7) Launch website

demo.launch(share=True)